openapi: 3.0.0
info:
  title: order-management-api
  version: '1.0'
  description: Api to add and read additional info for vipps orders
  contact:
    name: Team ecom
    url: 'https://vipps.no/kontakt-oss/bedrift/vipps/'
servers:
  - url: 'https://api.vipps.no/order-management'
    description: vipps order management api
paths:
  '/{version}/order/{vippsTransactionId}':
    parameters:
      - schema:
          type: string
        name: vippsTransactionId
        in: path
        required: true
      - $ref: '#/components/parameters/version'
    get:
      summary: Get info by vippsTransactionId
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                Retrieve order info:
                  value:
                    category: ticket
                    orderDetailsUrl: 'https://www.vipps.no'
                    imageIds:
                      - id: laptop_image4433
                        sortOrder: 1
        '404':
          description: Order Not Found
      operationId: getOrder
      description: Retrive the metadata for an order
      parameters: []
      tags:
        - Order
      security:
        - BearerToken: []
    put:
      summary: Add info to vippsTransactionId
      operationId: putOrder
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              Adding order metadata with one image:
                value:
                  category: general
                  orderDetailsUrl: 'https://www.vipps.no'
                  imageIds:
                    - id: laptop_image4433
                      sortOrder: 1
        description: ''
      description: 'Post additional information about an order that will show up on the vipps receipt. '
      parameters: []
      tags:
        - Order
      security:
        - BearerToken: []
  '/{version}/image':
    post:
      summary: Add an image to vipps
      operationId: postImage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageResponse'
              examples:
                example-1:
                  value:
                    imageId: laptop_image4433
      description: Endpoint for uploading images to Vipps. A imageId will be returned that can be used when adding metadata to Vipps Transactions
      parameters: []
      tags:
        - Image
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Image'
            examples:
              example-1:
                value:
                  imageId: laptop_image4433
                  src: iVBORw0KGgoAAAANSUhEUgAAAKsAAADVCAMAAAAfHv
                  type: base64
      security:
        - BearerToken: []
    parameters:
      - $ref: '#/components/parameters/version'
  '/{version}/receipt/{vippsTransactionId}':
    parameters:
      - schema:
          type: string
        name: vippsTransactionId
        in: path
        required: true
      - $ref: '#/components/parameters/version'
    post:
      summary: Store receipt by vippsTransactionId
      operationId: postReceipt
      responses:
        '200':
          description: ''
        '404':
          description: Order not Found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
      description: Endpoint for uploading receipts to Vipps.
      security:
        - BearerToken: []
      tags:
        - Receipt
    get:
      summary: Get receipt by vippsTransactionId
      operationId: getReceipt
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
      description: Endpoint for downloading receipts to Vipps.
      security:
        - BearerToken: []
      tags:
        - Receipt
components:
  schemas:
    Order:
      type: object
      x-examples:
        example-1:
          value:
            category: general
            orderDetailsUrl: 'https://www.vipps.no'
            imageIds:
              - id: laptop_image4433
                sortOrder: 1
      description: ''
      properties:
        category:
          type: string
          enum:
            - general
            - receipt
            - orderConfirmation
            - delivery
            - ticket
            - booking
          description: Enum containing different categories. These will be shown and might behave diferently in the app
        orderDetailsUrl:
          type: string
          example: 'https://www.vipps.no'
          format: uri
          description: URL linking back to the merchant.
          minLength: 1
        imageIds:
          description: list of imageIds linked to this transaction
          maxItems: 4
          type: array
          items:
            $ref: '#/components/schemas/ImageId'
      required:
        - category
        - orderDetailsUrl
    Image:
      type: object
      properties:
        imageId:
          description: Id of the image to be added
          maxLength: 128
          pattern: '^[0-9A-Za-z-_\.]+$'
          type: string
        src:
          type: string
          description: 'Src of the image, like a base64 encoded string'
        type:
          type: string
          enum:
            - base64
      required:
        - imageId
        - src
        - type
      x-examples:
        example-1:
          value:
            imageId: laptop_image4433
            src: iVBORw0KGgoAAAANSUhEUgAAAKsAAADVCAMAAAAfHv
            type: base64
    ImageResponse:
      type: object
      properties:
        imageId:
          type: string
      x-examples:
        example-1:
          imageId: laptop_image4433
    OrderLine:
      title: OrderLine
      type: object
      description: 'All numbers are interpreted as integers with two trailing zeros. ex: 10.00 = 1000'
      properties:
        amountExcludingTax:
          type: integer
          nullable: true
        amountIncludingTax:
          type: integer
          nullable: true
        description:
          type: string
        id:
          type: string
          description: The product ID
        productUrl:
          type: string
        quantity:
          type: integer
          nullable: true
        taxAmount:
          type: integer
          nullable: true
        taxPercentage:
          type: integer
          nullable: true
      required:
        - amountExcludingTax
        - amountIncludingTax
        - description
        - id
        - quantity
        - taxAmount
        - taxPercentage
    Receipt:
      title: Receipt
      type: object
      properties:
        OrderLines:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderLine'
      required:
        - OrderLines
    ImageId:
      title: ImageId
      type: object
      properties:
        id:
          type: string
          pattern: '^[0-9A-Za-z-_\.]+$'
          maxLength: 128
        sortOrder:
          type: integer
      required:
        - id
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
  parameters:
    version:
      name: version
      in: path
      required: true
      schema:
        type: string
        enum:
          - v1
      description: The service version number
tags:
  - name: Image
  - name: MobileOrder
  - name: Order
  - name: Receipt
